/**
 * Automatically generated by Zserio Java extension version 2.12.0.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode.
 */

package nds.localization._module;

public final class OCCUPANCY_GRID_LAYER_METADATA
{
    public static final java.lang.String OCCUPANCY_GRID_LAYER_METADATA = "localization.metadata.OccupancyGridLayerMetadata";
}
