# Automatically generated by Zserio Python extension version 2.12.0.
# Generator setup: writerCode, pubsubCode, serviceCode, sqlCode

import nds.core.types.flag

InVicinity = nds.core.types.flag.Flag
