/**
 * Automatically generated by Zserio Java extension version 2.12.0.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode.
 */

package nds.lane.reference.types;

public enum MarkingColor implements zserio.runtime.io.PackableWriter, zserio.runtime.PackableSizeOf,
        zserio.runtime.ZserioEnum
{
    UNKNOWN((short)0),
    WHITE((short)1),
    LIGHT_GRAY((short)2),
    GRAY((short)3),
    DARK_GRAY((short)4),
    BLACK((short)5),
    RED((short)6),
    YELLOW((short)7),
    GREEN((short)8),
    CYAN((short)9),
    BLUE((short)10),
    ORANGE((short)11),
    PURPLE((short)12);

    private MarkingColor(short value)
    {
        this.value = value;
    }

    public short getValue()
    {
        return value;
    }

    @Override
    public java.lang.Number getGenericValue()
    {
        return value;
    }

    @Override
    public void initPackingContext(zserio.runtime.array.PackingContext context)
    {
        final zserio.runtime.array.DeltaContext deltaContext = context.cast();
        deltaContext.init(
                new zserio.runtime.array.ArrayTraits.BitFieldShortArrayTraits(8),
                new zserio.runtime.array.ArrayElement.ShortArrayElement(value));
    }

    @Override
    public int bitSizeOf()
    {
        return bitSizeOf(0);
    }

    @Override
    public int bitSizeOf(long bitPosition)
    {
        return 8;
    }

    @Override
    public int bitSizeOf(zserio.runtime.array.PackingContext context, long bitPosition)
    {
        final zserio.runtime.array.DeltaContext deltaContext = context.cast();
        return deltaContext.bitSizeOf(
                new zserio.runtime.array.ArrayTraits.BitFieldShortArrayTraits(8),
                new zserio.runtime.array.ArrayElement.ShortArrayElement(value));
    }

    @Override
    public long initializeOffsets()
    {
        return initializeOffsets(0);
    }

    @Override
    public long initializeOffsets(long bitPosition) throws zserio.runtime.ZserioError
    {
        return bitPosition + bitSizeOf(bitPosition);
    }

    @Override
    public long initializeOffsets(zserio.runtime.array.PackingContext context, long bitPosition)
    {
        return bitPosition + bitSizeOf(context, bitPosition);
    }

    @Override
    public void write(zserio.runtime.io.BitStreamWriter out) throws java.io.IOException
    {
        out.writeUnsignedByte(getValue());
    }

    @Override
    public void write(zserio.runtime.array.PackingContext context, zserio.runtime.io.BitStreamWriter out)
            throws java.io.IOException
    {
        final zserio.runtime.array.DeltaContext deltaContext = context.cast();
        deltaContext.write(
                new zserio.runtime.array.ArrayTraits.BitFieldShortArrayTraits(8), out,
                new zserio.runtime.array.ArrayElement.ShortArrayElement(value));
    }

    public static MarkingColor readEnum(zserio.runtime.io.BitStreamReader in) throws java.io.IOException
    {
        return toEnum(in.readUnsignedByte());
    }

    public static MarkingColor readEnum(zserio.runtime.array.PackingContext context,
            zserio.runtime.io.BitStreamReader in) throws java.io.IOException
    {
        final zserio.runtime.array.DeltaContext deltaContext = context.cast();
        return toEnum(((zserio.runtime.array.ArrayElement.ShortArrayElement)
                deltaContext.read(
                        new zserio.runtime.array.ArrayTraits.BitFieldShortArrayTraits(8), in)).get());
    }

    public static MarkingColor toEnum(short value)
    {
        switch (value)
        {
            case (short)0:
                return UNKNOWN;
            case (short)1:
                return WHITE;
            case (short)2:
                return LIGHT_GRAY;
            case (short)3:
                return GRAY;
            case (short)4:
                return DARK_GRAY;
            case (short)5:
                return BLACK;
            case (short)6:
                return RED;
            case (short)7:
                return YELLOW;
            case (short)8:
                return GREEN;
            case (short)9:
                return CYAN;
            case (short)10:
                return BLUE;
            case (short)11:
                return ORANGE;
            case (short)12:
                return PURPLE;
            default:
                throw new java.lang.IllegalArgumentException(
                        "Unknown value for enumeration MarkingColor: " + value + "!");
        }
    }

    public static MarkingColor toEnum(java.lang.String itemName)
    {
        if (itemName.equals("UNKNOWN"))
            return UNKNOWN;
        if (itemName.equals("WHITE"))
            return WHITE;
        if (itemName.equals("LIGHT_GRAY"))
            return LIGHT_GRAY;
        if (itemName.equals("GRAY"))
            return GRAY;
        if (itemName.equals("DARK_GRAY"))
            return DARK_GRAY;
        if (itemName.equals("BLACK"))
            return BLACK;
        if (itemName.equals("RED"))
            return RED;
        if (itemName.equals("YELLOW"))
            return YELLOW;
        if (itemName.equals("GREEN"))
            return GREEN;
        if (itemName.equals("CYAN"))
            return CYAN;
        if (itemName.equals("BLUE"))
            return BLUE;
        if (itemName.equals("ORANGE"))
            return ORANGE;
        if (itemName.equals("PURPLE"))
            return PURPLE;
        throw new java.lang.IllegalArgumentException(
                "Enum item '" + itemName + "' doesn't exist in enumeration MarkingColor!");
    }

    private short value;
}
