/**
 * Automatically generated by Zserio Java extension version 2.12.0.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode.
 */

package nds.rules.instantiations;

public class RulesLaneTransitionAttribute implements zserio.runtime.io.Writer, zserio.runtime.SizeOf
{
    public RulesLaneTransitionAttribute(
            nds.rules.attributes.RulesLaneTransitionAttributeType attributeTypeCode_)
    {
        this.attributeTypeCode_ = attributeTypeCode_;
    }

    public RulesLaneTransitionAttribute(zserio.runtime.io.BitStreamReader in,
            nds.rules.attributes.RulesLaneTransitionAttributeType attributeTypeCode_)
            throws java.io.IOException
    {
        this.attributeTypeCode_ = attributeTypeCode_;

        read(in);
    }

    public RulesLaneTransitionAttribute(
            nds.rules.attributes.RulesLaneTransitionAttributeType attributeTypeCode_,
            nds.rules.attributes.RulesLaneTransitionAttributeValue attributeValue_)
    {
        this(attributeTypeCode_);

        setAttributeValue(attributeValue_);
    }

    @Override
    public int bitSizeOf()
    {
        return bitSizeOf(0);
    }

    @Override
    public int bitSizeOf(long bitPosition)
    {
        long endBitPosition = bitPosition;

        endBitPosition += attributeValue_.bitSizeOf(endBitPosition);

        return (int)(endBitPosition - bitPosition);
    }

    public nds.rules.attributes.RulesLaneTransitionAttributeType getAttributeTypeCode()
    {
        return this.attributeTypeCode_;
    }

    public nds.rules.attributes.RulesLaneTransitionAttributeValue getAttributeValue()
    {
        return attributeValue_;
    }

    public void setAttributeValue(nds.rules.attributes.RulesLaneTransitionAttributeValue attributeValue_)
    {
        this.attributeValue_ = attributeValue_;
    }

    @Override
    public boolean equals(java.lang.Object obj)
    {
        if (obj instanceof RulesLaneTransitionAttribute)
        {
            final RulesLaneTransitionAttribute that = (RulesLaneTransitionAttribute)obj;

            return
                    ((this.attributeTypeCode_ == null) ? that.attributeTypeCode_ == null : this.attributeTypeCode_.getValue() == that.attributeTypeCode_.getValue()) &&
                    ((attributeValue_ == null) ? that.attributeValue_ == null : attributeValue_.equals(that.attributeValue_));
        }

        return false;
    }

    @Override
    public int hashCode()
    {
        int result = zserio.runtime.HashCodeUtil.HASH_SEED;

        result = zserio.runtime.HashCodeUtil.calcHashCode(result, getAttributeTypeCode());
        result = zserio.runtime.HashCodeUtil.calcHashCode(result, attributeValue_);

        return result;
    }

    public void read(zserio.runtime.io.BitStreamReader in)
            throws java.io.IOException
    {
        attributeValue_ = new nds.rules.attributes.RulesLaneTransitionAttributeValue(in, getAttributeTypeCode());
    }

    @Override
    public long initializeOffsets()
    {
        return initializeOffsets(0);
    }

    @Override
    public long initializeOffsets(long bitPosition)
    {
        long endBitPosition = bitPosition;

        endBitPosition = attributeValue_.initializeOffsets(endBitPosition);

        return endBitPosition;
    }

    @Override
    public void write(zserio.runtime.io.BitStreamWriter out) throws java.io.IOException
    {
        // check parameters
        if (attributeValue_.getType() != (getAttributeTypeCode()))
        {
            throw new zserio.runtime.ZserioError("Write: Inconsistent parameter type for field RulesLaneTransitionAttribute.attributeValue!");
        }
        attributeValue_.write(out);
    }

    private final nds.rules.attributes.RulesLaneTransitionAttributeType attributeTypeCode_;
    private nds.rules.attributes.RulesLaneTransitionAttributeValue attributeValue_;
}
