/**
 * Automatically generated by Zserio C++ extension version 2.12.0.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode, sourcesAmalgamation, stdAllocator.
 */

#ifndef NDS_LOCALIZATION_INSTANTIATIONS_LANDMARK_LANE_ATTRIBUTE_MAP_LIST_H
#define NDS_LOCALIZATION_INSTANTIATIONS_LANDMARK_LANE_ATTRIBUTE_MAP_LIST_H

#include <zserio/CppRuntimeVersion.h>
#if CPP_EXTENSION_RUNTIME_VERSION_NUMBER != 2012000
    #error Version mismatch between Zserio runtime library and Zserio compiler!
    #error Please update your Zserio runtime library to the version 2.12.0.
#endif

#include <zserio/Traits.h>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/AllocatorPropagatingCopy.h>
#include <zserio/DeltaContext.h>
#include <memory>
#include <zserio/Array.h>
#include <zserio/ArrayTraits.h>
#include <zserio/Types.h>
#include <zserio/Vector.h>

#include <nds/core/geometry/CoordShift.h>
#include <nds/localization/instantiations/LandmarkAttributeMapListHeader.h>
#include <nds/localization/instantiations/LandmarkLaneAttributeMap.h>

namespace nds
{
namespace localization
{
namespace instantiations
{

class LandmarkLaneAttributeMapList
{
public:
    class ZserioPackingContext
    {
    public:
        ::zserio::DeltaContext& getNumMaps()
        {
            return m_numMaps_;
        }

        ::nds::localization::instantiations::LandmarkAttributeMapListHeader::ZserioPackingContext& getHeader()
        {
            return m_header_;
        }

    private:
        ::zserio::DeltaContext m_numMaps_;
        ::nds::localization::instantiations::LandmarkAttributeMapListHeader::ZserioPackingContext m_header_;
    };

    using allocator_type = ::std::allocator<uint8_t>;

    LandmarkLaneAttributeMapList() noexcept :
            LandmarkLaneAttributeMapList(allocator_type())
    {}

    explicit LandmarkLaneAttributeMapList(const allocator_type& allocator) noexcept;

    template <typename ZSERIO_T_header = ::nds::localization::instantiations::LandmarkAttributeMapListHeader,
            typename ZSERIO_T_maps = ::zserio::vector<::nds::localization::instantiations::LandmarkLaneAttributeMap>>
    LandmarkLaneAttributeMapList(
            uint32_t numMaps_,
            ZSERIO_T_header&& header_,
            ZSERIO_T_maps&& maps_,
            const allocator_type& allocator = allocator_type()) :
            LandmarkLaneAttributeMapList(allocator)
    {
        m_numMaps_ = numMaps_;
        m_header_ = ::std::forward<ZSERIO_T_header>(header_);
        m_maps_ = ZserioArrayType_maps(::std::forward<ZSERIO_T_maps>(maps_));
    }

    explicit LandmarkLaneAttributeMapList(::zserio::BitStreamReader& in,
            ::nds::core::geometry::CoordShift coordShift_, const allocator_type& allocator = allocator_type());
    explicit LandmarkLaneAttributeMapList(ZserioPackingContext& context,
            ::zserio::BitStreamReader& in,
            ::nds::core::geometry::CoordShift coordShift_, const allocator_type& allocator = allocator_type());

    ~LandmarkLaneAttributeMapList() = default;

    LandmarkLaneAttributeMapList(const LandmarkLaneAttributeMapList& other);
    LandmarkLaneAttributeMapList& operator=(const LandmarkLaneAttributeMapList& other);

    LandmarkLaneAttributeMapList(LandmarkLaneAttributeMapList&& other);
    LandmarkLaneAttributeMapList& operator=(LandmarkLaneAttributeMapList&& other);

    LandmarkLaneAttributeMapList(::zserio::PropagateAllocatorT,
            const LandmarkLaneAttributeMapList& other, const allocator_type& allocator);

    void initialize(
            ::nds::core::geometry::CoordShift coordShift_);
    bool isInitialized() const;
    void initializeChildren();

    ::nds::core::geometry::CoordShift getCoordShift() const;

    uint32_t getNumMaps() const;
    void setNumMaps(uint32_t numMaps_);

    const ::nds::localization::instantiations::LandmarkAttributeMapListHeader& getHeader() const;
    ::nds::localization::instantiations::LandmarkAttributeMapListHeader& getHeader();
    void setHeader(const ::nds::localization::instantiations::LandmarkAttributeMapListHeader& header_);
    void setHeader(::nds::localization::instantiations::LandmarkAttributeMapListHeader&& header_);

    const ::zserio::vector<::nds::localization::instantiations::LandmarkLaneAttributeMap>& getMaps() const;
    ::zserio::vector<::nds::localization::instantiations::LandmarkLaneAttributeMap>& getMaps();
    void setMaps(const ::zserio::vector<::nds::localization::instantiations::LandmarkLaneAttributeMap>& maps_);
    void setMaps(::zserio::vector<::nds::localization::instantiations::LandmarkLaneAttributeMap>&& maps_);

    void initPackingContext(ZserioPackingContext& context) const;

    size_t bitSizeOf(size_t bitPosition = 0) const;
    size_t bitSizeOf(ZserioPackingContext& context, size_t bitPosition) const;

    size_t initializeOffsets(size_t bitPosition = 0);
    size_t initializeOffsets(ZserioPackingContext& context, size_t bitPosition);

    bool operator==(const LandmarkLaneAttributeMapList& other) const;
    uint32_t hashCode() const;

    void write(::zserio::BitStreamWriter& out) const;
    void write(ZserioPackingContext& context, ::zserio::BitStreamWriter& out) const;

private:
    class ZserioArrayExpressions_maps
    {
    public:
        using OwnerType = LandmarkLaneAttributeMapList;

        static void initializeElement(LandmarkLaneAttributeMapList& owner,
                ::nds::localization::instantiations::LandmarkLaneAttributeMap& element, size_t index);
    };

    class ZserioElementFactory_maps
    {
    public:
        using OwnerType = LandmarkLaneAttributeMapList;

        static void create(LandmarkLaneAttributeMapList& owner,
                ::zserio::vector<::nds::localization::instantiations::LandmarkLaneAttributeMap>& array,
                ::zserio::BitStreamReader& in, size_t index);

        static void create(LandmarkLaneAttributeMapList& owner,
                ::zserio::vector<::nds::localization::instantiations::LandmarkLaneAttributeMap>& array,
                ::nds::localization::instantiations::LandmarkLaneAttributeMap::ZserioPackingContext& context,
                ::zserio::BitStreamReader& in, size_t index);
    };

    using ZserioArrayType_maps = ::zserio::Array<::zserio::vector<::nds::localization::instantiations::LandmarkLaneAttributeMap>, ::zserio::ObjectArrayTraits<::nds::localization::instantiations::LandmarkLaneAttributeMap, ZserioElementFactory_maps>, ::zserio::ArrayType::NORMAL, ZserioArrayExpressions_maps>;

    uint32_t readNumMaps(::zserio::BitStreamReader& in);
    uint32_t readNumMaps(ZserioPackingContext& context,
            ::zserio::BitStreamReader& in);
    ::nds::localization::instantiations::LandmarkAttributeMapListHeader readHeader(::zserio::BitStreamReader& in,
            const allocator_type& allocator);
    ::nds::localization::instantiations::LandmarkAttributeMapListHeader readHeader(ZserioPackingContext& context,
            ::zserio::BitStreamReader& in, const allocator_type& allocator);
    ZserioArrayType_maps readMaps(::zserio::BitStreamReader& in,
            const allocator_type& allocator);
    ZserioArrayType_maps readMaps(ZserioPackingContext& context,
            ::zserio::BitStreamReader& in, const allocator_type& allocator);

    ::nds::core::geometry::CoordShift m_coordShift_;
    bool m_isInitialized;
    uint32_t m_numMaps_;
    ::nds::localization::instantiations::LandmarkAttributeMapListHeader m_header_;
    ZserioArrayType_maps m_maps_;
};

} // namespace instantiations
} // namespace localization
} // namespace nds

#endif // NDS_LOCALIZATION_INSTANTIATIONS_LANDMARK_LANE_ATTRIBUTE_MAP_LIST_H
