/**
 * Automatically generated by Zserio C++ extension version 2.12.0.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode, sourcesAmalgamation, stdAllocator.
 */

#ifndef NDS_CORE_GEOMETRY_LINE_POSITION_OFFSET2_D_H
#define NDS_CORE_GEOMETRY_LINE_POSITION_OFFSET2_D_H

#include <zserio/CppRuntimeVersion.h>
#if CPP_EXTENSION_RUNTIME_VERSION_NUMBER != 2012000
    #error Version mismatch between Zserio runtime library and Zserio compiler!
    #error Please update your Zserio runtime library to the version 2.12.0.
#endif

#include <zserio/Traits.h>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/AllocatorPropagatingCopy.h>
#include <zserio/DeltaContext.h>
#include <memory>
#include <zserio/ArrayTraits.h>

#include <nds/core/geometry/CoordShift.h>
#include <nds/core/geometry/CoordWidth.h>
#include <nds/core/geometry/LinePosition.h>
#include <nds/core/geometry/PositionOffset2D.h>

namespace nds
{
namespace core
{
namespace geometry
{

class LinePositionOffset2D
{
public:
    class ZserioPackingContext
    {
    public:
        ::zserio::DeltaContext& getLinePosition()
        {
            return m_linePosition_;
        }

        ::zserio::DeltaContext& getNumBits()
        {
            return m_numBits_;
        }

        ::nds::core::geometry::PositionOffset2D::ZserioPackingContext& getOffset()
        {
            return m_offset_;
        }

    private:
        ::zserio::DeltaContext m_linePosition_;
        ::zserio::DeltaContext m_numBits_;
        ::nds::core::geometry::PositionOffset2D::ZserioPackingContext m_offset_;
    };

    using allocator_type = ::std::allocator<uint8_t>;

    LinePositionOffset2D() noexcept :
            LinePositionOffset2D(allocator_type())
    {}

    explicit LinePositionOffset2D(const allocator_type& allocator) noexcept;

    template <typename ZSERIO_T_offset = ::nds::core::geometry::PositionOffset2D>
    LinePositionOffset2D(
            ::nds::core::geometry::LinePosition linePosition_,
            ::nds::core::geometry::CoordWidth numBits_,
            ZSERIO_T_offset&& offset_,
            const allocator_type& allocator = allocator_type()) :
            LinePositionOffset2D(allocator)
    {
        m_linePosition_ = linePosition_;
        m_numBits_ = numBits_;
        m_offset_ = ::std::forward<ZSERIO_T_offset>(offset_);
    }

    explicit LinePositionOffset2D(::zserio::BitStreamReader& in,
            ::nds::core::geometry::CoordShift shift_, const allocator_type& allocator = allocator_type());
    explicit LinePositionOffset2D(ZserioPackingContext& context,
            ::zserio::BitStreamReader& in,
            ::nds::core::geometry::CoordShift shift_, const allocator_type& allocator = allocator_type());

    ~LinePositionOffset2D() = default;

    LinePositionOffset2D(const LinePositionOffset2D& other);
    LinePositionOffset2D& operator=(const LinePositionOffset2D& other);

    LinePositionOffset2D(LinePositionOffset2D&& other);
    LinePositionOffset2D& operator=(LinePositionOffset2D&& other);

    LinePositionOffset2D(::zserio::PropagateAllocatorT,
            const LinePositionOffset2D& other, const allocator_type& allocator);

    void initialize(
            ::nds::core::geometry::CoordShift shift_);
    bool isInitialized() const;
    void initializeChildren();

    ::nds::core::geometry::CoordShift getShift() const;

    ::nds::core::geometry::LinePosition getLinePosition() const;
    void setLinePosition(::nds::core::geometry::LinePosition linePosition_);

    ::nds::core::geometry::CoordWidth getNumBits() const;
    void setNumBits(::nds::core::geometry::CoordWidth numBits_);

    const ::nds::core::geometry::PositionOffset2D& getOffset() const;
    ::nds::core::geometry::PositionOffset2D& getOffset();
    void setOffset(const ::nds::core::geometry::PositionOffset2D& offset_);
    void setOffset(::nds::core::geometry::PositionOffset2D&& offset_);

    void initPackingContext(ZserioPackingContext& context) const;

    size_t bitSizeOf(size_t bitPosition = 0) const;
    size_t bitSizeOf(ZserioPackingContext& context, size_t bitPosition) const;

    size_t initializeOffsets(size_t bitPosition = 0);
    size_t initializeOffsets(ZserioPackingContext& context, size_t bitPosition);

    bool operator==(const LinePositionOffset2D& other) const;
    uint32_t hashCode() const;

    void write(::zserio::BitStreamWriter& out) const;
    void write(ZserioPackingContext& context, ::zserio::BitStreamWriter& out) const;

private:
    ::nds::core::geometry::LinePosition readLinePosition(::zserio::BitStreamReader& in);
    ::nds::core::geometry::LinePosition readLinePosition(ZserioPackingContext& context,
            ::zserio::BitStreamReader& in);
    ::nds::core::geometry::CoordWidth readNumBits(::zserio::BitStreamReader& in);
    ::nds::core::geometry::CoordWidth readNumBits(ZserioPackingContext& context,
            ::zserio::BitStreamReader& in);
    ::nds::core::geometry::PositionOffset2D readOffset(::zserio::BitStreamReader& in,
            const allocator_type& allocator);
    ::nds::core::geometry::PositionOffset2D readOffset(ZserioPackingContext& context,
            ::zserio::BitStreamReader& in, const allocator_type& allocator);

    ::nds::core::geometry::CoordShift m_shift_;
    bool m_isInitialized;
    ::nds::core::geometry::LinePosition m_linePosition_;
    ::nds::core::geometry::CoordWidth m_numBits_;
    ::nds::core::geometry::PositionOffset2D m_offset_;
};

} // namespace geometry
} // namespace core
} // namespace nds

#endif // NDS_CORE_GEOMETRY_LINE_POSITION_OFFSET2_D_H
