/**
 * Automatically generated by Zserio C++ extension version 2.12.0.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode, sourcesAmalgamation, stdAllocator.
 */

#ifndef NDS_LANE_METADATA_GEOMETRY_LAYER_TYPE_H
#define NDS_LANE_METADATA_GEOMETRY_LAYER_TYPE_H

#include <zserio/CppRuntimeVersion.h>
#if CPP_EXTENSION_RUNTIME_VERSION_NUMBER != 2012000
    #error Version mismatch between Zserio runtime library and Zserio compiler!
    #error Please update your Zserio runtime library to the version 2.12.0.
#endif

#include <array>

#include <zserio/Enums.h>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/DeltaContext.h>
#include <zserio/ArrayTraits.h>
#include <zserio/Types.h>

namespace nds
{
namespace lane
{
namespace metadata
{

enum class GeometryLayerType : uint8_t
{
    LANE_GEOMETRY = UINT8_C(0),
    ROAD_SURFACE = UINT8_C(1)
};

} // namespace metadata
} // namespace lane
} // namespace nds

namespace zserio
{

// This is full specialization of enumeration traits and methods for GeometryLayerType enumeration.
template <>
struct EnumTraits<::nds::lane::metadata::GeometryLayerType>
{
    static constexpr ::std::array<const char*, 2> names =
    {{
        "LANE_GEOMETRY",
        "ROAD_SURFACE"
    }};

    static constexpr ::std::array<::nds::lane::metadata::GeometryLayerType, 2> values =
    {{
        ::nds::lane::metadata::GeometryLayerType::LANE_GEOMETRY,
        ::nds::lane::metadata::GeometryLayerType::ROAD_SURFACE
    }};

    static constexpr const char* enumName = "GeometryLayerType";
};

template <>
size_t enumToOrdinal<::nds::lane::metadata::GeometryLayerType>(::nds::lane::metadata::GeometryLayerType value);

template <>
::nds::lane::metadata::GeometryLayerType valueToEnum<::nds::lane::metadata::GeometryLayerType>(
        typename ::std::underlying_type<::nds::lane::metadata::GeometryLayerType>::type rawValue);

template <>
uint32_t enumHashCode<::nds::lane::metadata::GeometryLayerType>(::nds::lane::metadata::GeometryLayerType value);

template <>
void initPackingContext<::zserio::DeltaContext, ::nds::lane::metadata::GeometryLayerType>(::zserio::DeltaContext& context, ::nds::lane::metadata::GeometryLayerType value);

template <>
size_t bitSizeOf<::nds::lane::metadata::GeometryLayerType>(::nds::lane::metadata::GeometryLayerType value);

template <>
size_t bitSizeOf<::zserio::DeltaContext, ::nds::lane::metadata::GeometryLayerType>(::zserio::DeltaContext& context, ::nds::lane::metadata::GeometryLayerType value);

template <>
size_t initializeOffsets<::nds::lane::metadata::GeometryLayerType>(size_t bitPosition, ::nds::lane::metadata::GeometryLayerType value);

template <>
size_t initializeOffsets<::zserio::DeltaContext, ::nds::lane::metadata::GeometryLayerType>(::zserio::DeltaContext& context, size_t bitPosition,
        ::nds::lane::metadata::GeometryLayerType value);

template <>
::nds::lane::metadata::GeometryLayerType read<::nds::lane::metadata::GeometryLayerType>(::zserio::BitStreamReader& in);

template <>
::nds::lane::metadata::GeometryLayerType read<::nds::lane::metadata::GeometryLayerType, ::zserio::DeltaContext>(::zserio::DeltaContext& context, ::zserio::BitStreamReader& in);

template <>
void write<::nds::lane::metadata::GeometryLayerType>(::zserio::BitStreamWriter& out, ::nds::lane::metadata::GeometryLayerType value);

template <>
void write<::zserio::DeltaContext, ::nds::lane::metadata::GeometryLayerType>(::zserio::DeltaContext& context, ::zserio::BitStreamWriter& out,
        ::nds::lane::metadata::GeometryLayerType value);

} // namespace zserio

#endif // NDS_LANE_METADATA_GEOMETRY_LAYER_TYPE_H
