/**
 * Automatically generated by Zserio C++ extension version 2.12.0.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode, sourcesAmalgamation, stdAllocator.
 */

#ifndef NDS_TRAFFIC_TYPES_TRAFFIC_EVENT_ID_H
#define NDS_TRAFFIC_TYPES_TRAFFIC_EVENT_ID_H

#include <zserio/CppRuntimeVersion.h>
#if CPP_EXTENSION_RUNTIME_VERSION_NUMBER != 2012000
    #error Version mismatch between Zserio runtime library and Zserio compiler!
    #error Please update your Zserio runtime library to the version 2.12.0.
#endif

#include <zserio/ArrayTraits.h>
#include <zserio/Types.h>

namespace nds
{
namespace traffic
{
namespace types
{

using TrafficEventId = uint64_t;

} // namespace types
} // namespace traffic
} // namespace nds

#endif // NDS_TRAFFIC_TYPES_TRAFFIC_EVENT_ID_H
