/**
 * Automatically generated by Zserio Java extension version 2.12.0.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode.
 */

package nds.road._module;

public final class ROAD_GEOMETRY_LAYER
{
    public static final java.lang.String ROAD_GEOMETRY_LAYER = "road.layer.RoadGeometryLayer";
}
