# Automatically generated by Zserio Python extension version 2.12.0.
# Generator setup: writerCode, pubsubCode, serviceCode, sqlCode

from __future__ import annotations

import typing
import zserio

import nds.core.geometry.coord_shift
import nds.core.geometry.line2d
import nds.road.reference.types.road_id

class AdasGeometryList:
    def __init__(
            self,
            shift_: nds.core.geometry.coord_shift.CoordShift,
            num_road_references_: int = int(),
            road_: typing.List[nds.road.reference.types.road_id.RoadId] = None,
            adas_geometry_: typing.List[nds.core.geometry.line2d.Line2D] = None) -> None:
        self._shift_ = shift_
        self._num_road_references_ = num_road_references_
        self._road_ = zserio.array.Array(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_road()), road_)
        self._adas_geometry_ = zserio.array.Array(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_adas_geometry(self)), adas_geometry_)

    @classmethod
    def from_reader(
            cls: typing.Type['AdasGeometryList'],
            zserio_reader: zserio.BitStreamReader,
            shift_: nds.core.geometry.coord_shift.CoordShift) -> 'AdasGeometryList':
        self = object.__new__(cls)
        self._shift_ = shift_

        self.read(zserio_reader)

        return self

    @classmethod
    def from_reader_packed(
            cls: typing.Type['AdasGeometryList'],
            zserio_context: AdasGeometryList.ZserioPackingContext,
            zserio_reader: zserio.BitStreamReader,
            shift_: nds.core.geometry.coord_shift.CoordShift) -> 'AdasGeometryList':
        self = object.__new__(cls)
        self._shift_ = shift_

        self.read_packed(zserio_context, zserio_reader)

        return self

    def __eq__(self, other: object) -> bool:
        if isinstance(other, AdasGeometryList):
            return (self._shift_ == other._shift_ and
                    (self._num_road_references_ == other._num_road_references_) and
                    (self._road_ == other._road_) and
                    (self._adas_geometry_ == other._adas_geometry_))

        return False

    def __hash__(self) -> int:
        result = zserio.hashcode.HASH_SEED
        result = zserio.hashcode.calc_hashcode_int32(result, self._shift_)
        result = zserio.hashcode.calc_hashcode_int64(result, self._num_road_references_)
        result = zserio.hashcode.calc_hashcode_object(result, self._road_)
        result = zserio.hashcode.calc_hashcode_object(result, self._adas_geometry_)

        return result

    @property
    def shift(self) -> nds.core.geometry.coord_shift.CoordShift:
        return self._shift_

    @property
    def num_road_references(self) -> int:
        return self._num_road_references_

    @num_road_references.setter
    def num_road_references(self, num_road_references_: int) -> None:
        self._num_road_references_ = num_road_references_

    @property
    def road(self) -> typing.List[nds.road.reference.types.road_id.RoadId]:
        return self._road_.raw_array

    @road.setter
    def road(self, road_: typing.List[nds.road.reference.types.road_id.RoadId]) -> None:
        self._road_ = zserio.array.Array(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_road()), road_)

    @property
    def adas_geometry(self) -> typing.List[nds.core.geometry.line2d.Line2D]:
        return self._adas_geometry_.raw_array

    @adas_geometry.setter
    def adas_geometry(self, adas_geometry_: typing.List[nds.core.geometry.line2d.Line2D]) -> None:
        self._adas_geometry_ = zserio.array.Array(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_adas_geometry(self)), adas_geometry_)

    def init_packing_context(self, zserio_context: AdasGeometryList.ZserioPackingContext) -> None:
        zserio_context.num_road_references.init(zserio.array.VarSizeArrayTraits(), self._num_road_references_)

    def bitsizeof(self, bitposition: int = 0) -> int:
        end_bitposition = bitposition
        end_bitposition += zserio.bitsizeof.bitsizeof_varsize(self._num_road_references_)
        end_bitposition += self._road_.bitsizeof(end_bitposition)
        end_bitposition += self._adas_geometry_.bitsizeof(end_bitposition)

        return end_bitposition - bitposition

    def bitsizeof_packed(self, zserio_context: AdasGeometryList.ZserioPackingContext, bitposition: int = 0) -> int:
        end_bitposition = bitposition
        end_bitposition += zserio_context.num_road_references.bitsizeof(zserio.array.VarSizeArrayTraits(), self._num_road_references_)
        end_bitposition += self._road_.bitsizeof_packed(end_bitposition)
        end_bitposition += self._adas_geometry_.bitsizeof_packed(end_bitposition)

        return end_bitposition - bitposition

    def initialize_offsets(self, bitposition: int = 0) -> int:
        end_bitposition = bitposition
        end_bitposition += zserio.bitsizeof.bitsizeof_varsize(self._num_road_references_)
        end_bitposition = self._road_.initialize_offsets(end_bitposition)
        end_bitposition = self._adas_geometry_.initialize_offsets(end_bitposition)

        return end_bitposition

    def initialize_offsets_packed(self, zserio_context: AdasGeometryList.ZserioPackingContext, bitposition: int) -> int:
        end_bitposition = bitposition
        end_bitposition += zserio_context.num_road_references.bitsizeof(zserio.array.VarSizeArrayTraits(), self._num_road_references_)
        end_bitposition = self._road_.initialize_offsets_packed(end_bitposition)
        end_bitposition = self._adas_geometry_.initialize_offsets_packed(end_bitposition)

        return end_bitposition

    def read(self, zserio_reader: zserio.BitStreamReader) -> None:
        self._num_road_references_ = zserio_reader.read_varsize()
        self._road_ = zserio.array.Array.from_reader(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_road()), zserio_reader, self._num_road_references_)
        self._adas_geometry_ = zserio.array.Array.from_reader(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_adas_geometry(self)), zserio_reader, self._num_road_references_)

    def read_packed(self, zserio_context: AdasGeometryList.ZserioPackingContext, zserio_reader: zserio.BitStreamReader) -> None:
        self._num_road_references_ = zserio_context.num_road_references.read(zserio.array.VarSizeArrayTraits(), zserio_reader)

        self._road_ = zserio.array.Array.from_reader_packed(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_road()), zserio_reader, self._num_road_references_)

        self._adas_geometry_ = zserio.array.Array.from_reader_packed(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_adas_geometry(self)), zserio_reader, self._num_road_references_)

    def write(self, zserio_writer: zserio.BitStreamWriter) -> None:
        zserio_writer.write_varsize(self._num_road_references_)

        # check array length
        if len(self._road_) != (self._num_road_references_):
            raise zserio.PythonRuntimeException("Wrong array length for field AdasGeometryList.road: "
                                                f"{len(self._road_)} != {self._num_road_references_}!")
        self._road_.write(zserio_writer)

        # check array length
        if len(self._adas_geometry_) != (self._num_road_references_):
            raise zserio.PythonRuntimeException("Wrong array length for field AdasGeometryList.adasGeometry: "
                                                f"{len(self._adas_geometry_)} != {self._num_road_references_}!")
        self._adas_geometry_.write(zserio_writer)

    def write_packed(self, zserio_context: AdasGeometryList.ZserioPackingContext,
                     zserio_writer: zserio.BitStreamWriter) -> None:
        zserio_context.num_road_references.write(zserio.array.VarSizeArrayTraits(), zserio_writer, self._num_road_references_)

        # check array length
        if len(self._road_) != (self._num_road_references_):
            raise zserio.PythonRuntimeException("Wrong array length for field AdasGeometryList.road: "
                                                f"{len(self._road_)} != {self._num_road_references_}!")
        self._road_.write_packed(zserio_writer)

        # check array length
        if len(self._adas_geometry_) != (self._num_road_references_):
            raise zserio.PythonRuntimeException("Wrong array length for field AdasGeometryList.adasGeometry: "
                                                f"{len(self._adas_geometry_)} != {self._num_road_references_}!")
        self._adas_geometry_.write_packed(zserio_writer)

    class ZserioPackingContext:
        def __init__(self):
            self._num_road_references_ = zserio.array.DeltaContext()

        @property
        def num_road_references(self):
            return self._num_road_references_

    class _ZserioElementFactory_road:
        IS_OBJECT_PACKABLE = True

        @staticmethod
        def create(zserio_reader: zserio.BitStreamReader, zserio_index: int) -> nds.road.reference.types.road_id.RoadId:
            del zserio_index
            return nds.road.reference.types.road_id.RoadId.from_reader(zserio_reader)

        @staticmethod
        def create_packing_context() -> nds.road.reference.types.road_id.RoadId.ZserioPackingContext:
            return nds.road.reference.types.road_id.RoadId.ZserioPackingContext()

        @staticmethod
        def create_packed(zserio_context: nds.road.reference.types.road_id.RoadId.ZserioPackingContext,
                          zserio_reader: zserio.BitStreamReader, zserio_index: int) -> nds.road.reference.types.road_id.RoadId:
            del zserio_index
            return nds.road.reference.types.road_id.RoadId.from_reader_packed(zserio_context, zserio_reader)

    class _ZserioElementFactory_adas_geometry:
        IS_OBJECT_PACKABLE = True

        def __init__(self, owner):
            self._owner = owner

        def create(self, zserio_reader: zserio.BitStreamReader, zserio_index: int) -> nds.core.geometry.line2d.Line2D:
            del zserio_index
            return nds.core.geometry.line2d.Line2D.from_reader(zserio_reader, self._owner._shift_)

        @staticmethod
        def create_packing_context() -> nds.core.geometry.line2d.Line2D.ZserioPackingContext:
            return nds.core.geometry.line2d.Line2D.ZserioPackingContext()

        def create_packed(self, zserio_context: nds.core.geometry.line2d.Line2D.ZserioPackingContext,
                          zserio_reader: zserio.BitStreamReader, zserio_index: int) -> nds.core.geometry.line2d.Line2D:
            del zserio_index
            return nds.core.geometry.line2d.Line2D.from_reader_packed(zserio_context, zserio_reader, self._owner._shift_)
