/**
 * Automatically generated by Zserio C++ extension version 2.12.0.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode, sourcesAmalgamation, stdAllocator.
 */

#ifndef NDS_REGISTRY_NODE_SERVICE_PRIORITY_H
#define NDS_REGISTRY_NODE_SERVICE_PRIORITY_H

#include <zserio/CppRuntimeVersion.h>
#if CPP_EXTENSION_RUNTIME_VERSION_NUMBER != 2012000
    #error Version mismatch between Zserio runtime library and Zserio compiler!
    #error Please update your Zserio runtime library to the version 2.12.0.
#endif

#include <zserio/ArrayTraits.h>
#include <zserio/Types.h>

namespace nds
{
namespace registry
{
namespace node
{

using ServicePriority = uint8_t;

} // namespace node
} // namespace registry
} // namespace nds

#endif // NDS_REGISTRY_NODE_SERVICE_PRIORITY_H
