/**
 * Automatically generated by Zserio C++ extension version 2.12.0.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode, sourcesAmalgamation, stdAllocator.
 */

#ifndef NDS_DISPLAY_REFERENCE_TYPES_DISPLAY_LINE_GEOMETRY_OFFSET_POSITION_H
#define NDS_DISPLAY_REFERENCE_TYPES_DISPLAY_LINE_GEOMETRY_OFFSET_POSITION_H

#include <zserio/CppRuntimeVersion.h>
#if CPP_EXTENSION_RUNTIME_VERSION_NUMBER != 2012000
    #error Version mismatch between Zserio runtime library and Zserio compiler!
    #error Please update your Zserio runtime library to the version 2.12.0.
#endif

#include <zserio/ArrayTraits.h>

#include <nds/core/geometry/LinePositionOffset2D.h>

namespace nds
{
namespace display
{
namespace reference
{
namespace types
{

using DisplayLineGeometryOffsetPosition = ::nds::core::geometry::LinePositionOffset2D;

} // namespace types
} // namespace reference
} // namespace display
} // namespace nds

#endif // NDS_DISPLAY_REFERENCE_TYPES_DISPLAY_LINE_GEOMETRY_OFFSET_POSITION_H
