/*
 * Copyright (c) 2017-2022 SENSORIS Innovation Platform hosted by ERTICO - ITS Europe.
 *
 * This program and the accompanying materials are made available under the terms of the Creative Commons Attribution-NoDerivatives 4.0 International license which accompanies this distribution, and is available at https://creativecommons.org/licenses/by-nd/4.0/legalcode.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensoris/protobuf/types/base.proto

// Protobuf Java Version: 3.25.1
package org.sensoris.types.base;

public interface Int64GaussianDistributionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensoris.protobuf.types.base.Int64GaussianDistribution)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Timestamp interval.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.TimestampInterval timestamp_interval = 1;</code>
   * @return Whether the timestampInterval field is set.
   */
  boolean hasTimestampInterval();
  /**
   * <pre>
   * Timestamp interval.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.TimestampInterval timestamp_interval = 1;</code>
   * @return The timestampInterval.
   */
  org.sensoris.types.base.TimestampInterval getTimestampInterval();
  /**
   * <pre>
   * Timestamp interval.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.TimestampInterval timestamp_interval = 1;</code>
   */
  org.sensoris.types.base.TimestampIntervalOrBuilder getTimestampIntervalOrBuilder();

  /**
   * <pre>
   * Mean.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value mean = 2;</code>
   * @return Whether the mean field is set.
   */
  boolean hasMean();
  /**
   * <pre>
   * Mean.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value mean = 2;</code>
   * @return The mean.
   */
  com.google.protobuf.Int64Value getMean();
  /**
   * <pre>
   * Mean.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value mean = 2;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getMeanOrBuilder();

  /**
   * <pre>
   * Variance.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value variance = 3;</code>
   * @return Whether the variance field is set.
   */
  boolean hasVariance();
  /**
   * <pre>
   * Variance.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value variance = 3;</code>
   * @return The variance.
   */
  com.google.protobuf.Int64Value getVariance();
  /**
   * <pre>
   * Variance.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value variance = 3;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getVarianceOrBuilder();
}
