# Automatically generated by Zserio Python extension version 2.12.0.
# Generator setup: writerCode, pubsubCode, serviceCode, sqlCode

from __future__ import annotations

import typing
import zserio

class RoadCharacsLayerContent:
    def __init__(self) -> None:
        self._value = 0

    @classmethod
    def from_value(cls: typing.Type['RoadCharacsLayerContent'], value: int) -> 'RoadCharacsLayerContent':
        if value < 0 or value > 536870911:
            raise zserio.PythonRuntimeException(f"Value for bitmask 'RoadCharacsLayerContent' out of bounds: {value}!")

        instance = cls()
        instance._value = value
        return instance

    @classmethod
    def from_reader(cls: typing.Type['RoadCharacsLayerContent'], reader: zserio.BitStreamReader) -> 'RoadCharacsLayerContent':
        instance = cls()
        instance._value = reader.read_varuint32()
        return instance

    @classmethod
    def from_reader_packed(cls: typing.Type['RoadCharacsLayerContent'],
                           delta_context: zserio.array.DeltaContext,
                           reader: zserio.BitStreamReader) -> 'RoadCharacsLayerContent':
        instance = cls()
        instance._value = delta_context.read(zserio.array.VarUInt32ArrayTraits(),
                                             reader)
        return instance

    def __eq__(self, other: object) -> bool:
        if isinstance(other, RoadCharacsLayerContent):
            return self._value == other._value

        return False

    def __hash__(self) -> int:
        result = zserio.hashcode.HASH_SEED
        result = zserio.hashcode.calc_hashcode_int32(result, self._value)
        return result

    def __str__(self) -> str:
        result = ""

        if (self & RoadCharacsLayerContent.Values.ROAD_RANGE_MAPS) == RoadCharacsLayerContent.Values.ROAD_RANGE_MAPS:
            result += "ROAD_RANGE_MAPS" if not result else " | ROAD_RANGE_MAPS"
        if (self & RoadCharacsLayerContent.Values.ROAD_RANGE_SETS) == RoadCharacsLayerContent.Values.ROAD_RANGE_SETS:
            result += "ROAD_RANGE_SETS" if not result else " | ROAD_RANGE_SETS"
        if (self & RoadCharacsLayerContent.Values.ROAD_POSITION_MAPS) == RoadCharacsLayerContent.Values.ROAD_POSITION_MAPS:
            result += "ROAD_POSITION_MAPS" if not result else " | ROAD_POSITION_MAPS"
        if (self & RoadCharacsLayerContent.Values.ROAD_POSITION_SETS) == RoadCharacsLayerContent.Values.ROAD_POSITION_SETS:
            result += "ROAD_POSITION_SETS" if not result else " | ROAD_POSITION_SETS"
        if (self & RoadCharacsLayerContent.Values.TRANSITION_MAPS) == RoadCharacsLayerContent.Values.TRANSITION_MAPS:
            result += "TRANSITION_MAPS" if not result else " | TRANSITION_MAPS"
        if (self & RoadCharacsLayerContent.Values.TRANSITION_SETS) == RoadCharacsLayerContent.Values.TRANSITION_SETS:
            result += "TRANSITION_SETS" if not result else " | TRANSITION_SETS"

        return str(self._value) + "[" + result + "]"

    def __or__(self, other: 'RoadCharacsLayerContent') -> 'RoadCharacsLayerContent':
        return RoadCharacsLayerContent.from_value(self._value | other._value)

    def __and__(self, other: 'RoadCharacsLayerContent') -> 'RoadCharacsLayerContent':
        return RoadCharacsLayerContent.from_value(self._value & other._value)

    def __xor__(self, other: 'RoadCharacsLayerContent') -> 'RoadCharacsLayerContent':
        return RoadCharacsLayerContent.from_value(self._value ^ other._value)

    def __invert__(self) -> 'RoadCharacsLayerContent':
        return RoadCharacsLayerContent.from_value(~self._value & 536870911)

    @staticmethod
    def create_packing_context() -> zserio.array.DeltaContext:
        return zserio.array.DeltaContext()

    def init_packing_context(self, delta_context: zserio.array.DeltaContext) -> None:
        delta_context.init(zserio.array.VarUInt32ArrayTraits(), self._value)

    def bitsizeof(self, _bitposition: int = 0) -> int:
        return zserio.bitsizeof.bitsizeof_varuint32(self._value)

    def bitsizeof_packed(self, delta_context: zserio.array.DeltaContext, _bitposition: int) -> int:
        return delta_context.bitsizeof(zserio.array.VarUInt32ArrayTraits(),
                                       self._value)

    def initialize_offsets(self, bitposition: int = 0) -> int:
        return bitposition + self.bitsizeof(bitposition)

    def initialize_offsets_packed(self, delta_context: zserio.array.DeltaContext, bitposition: int) -> int:
        return bitposition + self.bitsizeof_packed(delta_context, bitposition)

    def write(self, writer: zserio.BitStreamWriter) -> None:
        writer.write_varuint32(self._value)

    def write_packed(self, delta_context: zserio.array.DeltaContext, writer: zserio.BitStreamWriter) -> None:
        delta_context.write(zserio.array.VarUInt32ArrayTraits(),
                            writer, self._value)

    @property
    def value(self) -> int:
        return self._value

    class Values:
        ROAD_RANGE_MAPS: 'RoadCharacsLayerContent' = None
        ROAD_RANGE_SETS: 'RoadCharacsLayerContent' = None
        ROAD_POSITION_MAPS: 'RoadCharacsLayerContent' = None
        ROAD_POSITION_SETS: 'RoadCharacsLayerContent' = None
        TRANSITION_MAPS: 'RoadCharacsLayerContent' = None
        TRANSITION_SETS: 'RoadCharacsLayerContent' = None

RoadCharacsLayerContent.Values.ROAD_RANGE_MAPS = RoadCharacsLayerContent.from_value(1)
RoadCharacsLayerContent.Values.ROAD_RANGE_SETS = RoadCharacsLayerContent.from_value(2)
RoadCharacsLayerContent.Values.ROAD_POSITION_MAPS = RoadCharacsLayerContent.from_value(4)
RoadCharacsLayerContent.Values.ROAD_POSITION_SETS = RoadCharacsLayerContent.from_value(8)
RoadCharacsLayerContent.Values.TRANSITION_MAPS = RoadCharacsLayerContent.from_value(16)
RoadCharacsLayerContent.Values.TRANSITION_SETS = RoadCharacsLayerContent.from_value(32)
