# Automatically generated by Zserio Python extension version 2.12.0.
# Generator setup: writerCode, pubsubCode, serviceCode, sqlCode

import nds.lane.metadata.geometry_layer_metadata

RoadSurfaceLayerMetadata = nds.lane.metadata.geometry_layer_metadata.GeometryLayerMetadata
