/**
 * Automatically generated by Zserio Java extension version 2.12.0.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode.
 */

package nds.smart.object;

public final class GLOBAL_ICONS
{
    public static final int GLOBAL_ICONS = 6;
}
