# Automatically generated by Zserio Python extension version 2.12.0.
# Generator setup: writerCode, pubsubCode, serviceCode, sqlCode

from __future__ import annotations

import typing
import zserio

import nds.core.geometry.coord_shift
import nds.road.reference.types.road_range_validity
import nds.road.reference.types.road_reference

class RegionRoadRelationList:
    def __init__(
            self,
            shift_: nds.core.geometry.coord_shift.CoordShift = nds.core.geometry.coord_shift.CoordShift(),
            num_relations_: int = int(),
            road_ids_: typing.List[nds.road.reference.types.road_reference.RoadReference] = None,
            road_range_validity_: typing.List[nds.road.reference.types.road_range_validity.RoadRangeValidity] = None) -> None:
        self._shift_ = shift_
        self._num_relations_ = num_relations_
        self._road_ids_ = zserio.array.Array(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_road_ids()), road_ids_)
        self._road_range_validity_ = zserio.array.Array(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_road_range_validity(self)), road_range_validity_)

    @classmethod
    def from_reader(
            cls: typing.Type['RegionRoadRelationList'],
            zserio_reader: zserio.BitStreamReader) -> 'RegionRoadRelationList':
        self = object.__new__(cls)

        self.read(zserio_reader)

        return self

    @classmethod
    def from_reader_packed(
            cls: typing.Type['RegionRoadRelationList'],
            zserio_context: RegionRoadRelationList.ZserioPackingContext,
            zserio_reader: zserio.BitStreamReader) -> 'RegionRoadRelationList':
        self = object.__new__(cls)

        self.read_packed(zserio_context, zserio_reader)

        return self

    def __eq__(self, other: object) -> bool:
        if isinstance(other, RegionRoadRelationList):
            return ((self._shift_ == other._shift_) and
                    (self._num_relations_ == other._num_relations_) and
                    (self._road_ids_ == other._road_ids_) and
                    (self._road_range_validity_ == other._road_range_validity_))

        return False

    def __hash__(self) -> int:
        result = zserio.hashcode.HASH_SEED
        result = zserio.hashcode.calc_hashcode_int32(result, self._shift_)
        result = zserio.hashcode.calc_hashcode_int64(result, self._num_relations_)
        result = zserio.hashcode.calc_hashcode_object(result, self._road_ids_)
        result = zserio.hashcode.calc_hashcode_object(result, self._road_range_validity_)

        return result

    @property
    def shift(self) -> nds.core.geometry.coord_shift.CoordShift:
        return self._shift_

    @shift.setter
    def shift(self, shift_: nds.core.geometry.coord_shift.CoordShift) -> None:
        self._shift_ = shift_

    @property
    def num_relations(self) -> int:
        return self._num_relations_

    @num_relations.setter
    def num_relations(self, num_relations_: int) -> None:
        self._num_relations_ = num_relations_

    @property
    def road_ids(self) -> typing.List[nds.road.reference.types.road_reference.RoadReference]:
        return self._road_ids_.raw_array

    @road_ids.setter
    def road_ids(self, road_ids_: typing.List[nds.road.reference.types.road_reference.RoadReference]) -> None:
        self._road_ids_ = zserio.array.Array(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_road_ids()), road_ids_)

    @property
    def road_range_validity(self) -> typing.List[nds.road.reference.types.road_range_validity.RoadRangeValidity]:
        return self._road_range_validity_.raw_array

    @road_range_validity.setter
    def road_range_validity(self, road_range_validity_: typing.List[nds.road.reference.types.road_range_validity.RoadRangeValidity]) -> None:
        self._road_range_validity_ = zserio.array.Array(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_road_range_validity(self)), road_range_validity_)

    def init_packing_context(self, zserio_context: RegionRoadRelationList.ZserioPackingContext) -> None:
        zserio_context.shift.init(zserio.array.BitFieldArrayTraits(5), self._shift_)
        zserio_context.num_relations.init(zserio.array.VarSizeArrayTraits(), self._num_relations_)

    def bitsizeof(self, bitposition: int = 0) -> int:
        end_bitposition = bitposition
        end_bitposition += 5
        end_bitposition += zserio.bitsizeof.bitsizeof_varsize(self._num_relations_)
        end_bitposition += self._road_ids_.bitsizeof(end_bitposition)
        end_bitposition += self._road_range_validity_.bitsizeof(end_bitposition)

        return end_bitposition - bitposition

    def bitsizeof_packed(self, zserio_context: RegionRoadRelationList.ZserioPackingContext, bitposition: int = 0) -> int:
        end_bitposition = bitposition
        end_bitposition += zserio_context.shift.bitsizeof(zserio.array.BitFieldArrayTraits(5), self._shift_)
        end_bitposition += zserio_context.num_relations.bitsizeof(zserio.array.VarSizeArrayTraits(), self._num_relations_)
        end_bitposition += self._road_ids_.bitsizeof_packed(end_bitposition)
        end_bitposition += self._road_range_validity_.bitsizeof_packed(end_bitposition)

        return end_bitposition - bitposition

    def initialize_offsets(self, bitposition: int = 0) -> int:
        end_bitposition = bitposition
        end_bitposition += 5
        end_bitposition += zserio.bitsizeof.bitsizeof_varsize(self._num_relations_)
        end_bitposition = self._road_ids_.initialize_offsets(end_bitposition)
        end_bitposition = self._road_range_validity_.initialize_offsets(end_bitposition)

        return end_bitposition

    def initialize_offsets_packed(self, zserio_context: RegionRoadRelationList.ZserioPackingContext, bitposition: int) -> int:
        end_bitposition = bitposition
        end_bitposition += zserio_context.shift.bitsizeof(zserio.array.BitFieldArrayTraits(5), self._shift_)
        end_bitposition += zserio_context.num_relations.bitsizeof(zserio.array.VarSizeArrayTraits(), self._num_relations_)
        end_bitposition = self._road_ids_.initialize_offsets_packed(end_bitposition)
        end_bitposition = self._road_range_validity_.initialize_offsets_packed(end_bitposition)

        return end_bitposition

    def read(self, zserio_reader: zserio.BitStreamReader) -> None:
        self._shift_ = zserio_reader.read_bits(5)
        self._num_relations_ = zserio_reader.read_varsize()
        self._road_ids_ = zserio.array.Array.from_reader(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_road_ids()), zserio_reader, self._num_relations_)
        self._road_range_validity_ = zserio.array.Array.from_reader(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_road_range_validity(self)), zserio_reader, self._num_relations_)

    def read_packed(self, zserio_context: RegionRoadRelationList.ZserioPackingContext, zserio_reader: zserio.BitStreamReader) -> None:
        self._shift_ = zserio_context.shift.read(zserio.array.BitFieldArrayTraits(5), zserio_reader)

        self._num_relations_ = zserio_context.num_relations.read(zserio.array.VarSizeArrayTraits(), zserio_reader)

        self._road_ids_ = zserio.array.Array.from_reader_packed(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_road_ids()), zserio_reader, self._num_relations_)

        self._road_range_validity_ = zserio.array.Array.from_reader_packed(zserio.array.ObjectArrayTraits(self._ZserioElementFactory_road_range_validity(self)), zserio_reader, self._num_relations_)

    def write(self, zserio_writer: zserio.BitStreamWriter) -> None:
        zserio_writer.write_bits(self._shift_, 5)

        zserio_writer.write_varsize(self._num_relations_)

        # check array length
        if len(self._road_ids_) != (self._num_relations_):
            raise zserio.PythonRuntimeException("Wrong array length for field RegionRoadRelationList.roadIds: "
                                                f"{len(self._road_ids_)} != {self._num_relations_}!")
        self._road_ids_.write(zserio_writer)

        # check array length
        if len(self._road_range_validity_) != (self._num_relations_):
            raise zserio.PythonRuntimeException("Wrong array length for field RegionRoadRelationList.roadRangeValidity: "
                                                f"{len(self._road_range_validity_)} != {self._num_relations_}!")
        self._road_range_validity_.write(zserio_writer)

    def write_packed(self, zserio_context: RegionRoadRelationList.ZserioPackingContext,
                     zserio_writer: zserio.BitStreamWriter) -> None:
        zserio_context.shift.write(zserio.array.BitFieldArrayTraits(5), zserio_writer, self._shift_)

        zserio_context.num_relations.write(zserio.array.VarSizeArrayTraits(), zserio_writer, self._num_relations_)

        # check array length
        if len(self._road_ids_) != (self._num_relations_):
            raise zserio.PythonRuntimeException("Wrong array length for field RegionRoadRelationList.roadIds: "
                                                f"{len(self._road_ids_)} != {self._num_relations_}!")
        self._road_ids_.write_packed(zserio_writer)

        # check array length
        if len(self._road_range_validity_) != (self._num_relations_):
            raise zserio.PythonRuntimeException("Wrong array length for field RegionRoadRelationList.roadRangeValidity: "
                                                f"{len(self._road_range_validity_)} != {self._num_relations_}!")
        self._road_range_validity_.write_packed(zserio_writer)

    class ZserioPackingContext:
        def __init__(self):
            self._shift_ = zserio.array.DeltaContext()
            self._num_relations_ = zserio.array.DeltaContext()

        @property
        def shift(self):
            return self._shift_

        @property
        def num_relations(self):
            return self._num_relations_

    class _ZserioElementFactory_road_ids:
        IS_OBJECT_PACKABLE = True

        @staticmethod
        def create(zserio_reader: zserio.BitStreamReader, zserio_index: int) -> nds.road.reference.types.road_reference.RoadReference:
            del zserio_index
            return nds.road.reference.types.road_reference.RoadReference.from_reader(zserio_reader)

        @staticmethod
        def create_packing_context() -> nds.road.reference.types.road_reference.RoadReference.ZserioPackingContext:
            return nds.road.reference.types.road_reference.RoadReference.ZserioPackingContext()

        @staticmethod
        def create_packed(zserio_context: nds.road.reference.types.road_reference.RoadReference.ZserioPackingContext,
                          zserio_reader: zserio.BitStreamReader, zserio_index: int) -> nds.road.reference.types.road_reference.RoadReference:
            del zserio_index
            return nds.road.reference.types.road_reference.RoadReference.from_reader_packed(zserio_context, zserio_reader)

    class _ZserioElementFactory_road_range_validity:
        IS_OBJECT_PACKABLE = True

        def __init__(self, owner):
            self._owner = owner

        def create(self, zserio_reader: zserio.BitStreamReader, zserio_index: int) -> nds.road.reference.types.road_range_validity.RoadRangeValidity:
            del zserio_index
            return nds.road.reference.types.road_range_validity.RoadRangeValidity.from_reader(zserio_reader, self._owner._shift_)

        @staticmethod
        def create_packing_context() -> nds.road.reference.types.road_range_validity.RoadRangeValidity.ZserioPackingContext:
            return nds.road.reference.types.road_range_validity.RoadRangeValidity.ZserioPackingContext()

        def create_packed(self, zserio_context: nds.road.reference.types.road_range_validity.RoadRangeValidity.ZserioPackingContext,
                          zserio_reader: zserio.BitStreamReader, zserio_index: int) -> nds.road.reference.types.road_range_validity.RoadRangeValidity:
            del zserio_index
            return nds.road.reference.types.road_range_validity.RoadRangeValidity.from_reader_packed(zserio_context, zserio_reader, self._owner._shift_)
